version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:3001"  # porta do host : porta do container

  backend:
    build: ./backend
    ports:
      - "3333:3333"

  db1:
    image: postgres:latest
    environment:
      POSTGRES_USER: jessi_sd
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: db1
    volumes:
      - ./db1-init:/docker-entrypoint-initdb.d

  db2:
    image: postgres:latest
    environment:
      POSTGRES_USER: jessi_sd
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: db2
    volumes:
      - ./db2-init:/docker-entrypoint-initdb.d

volumes:
  db1-data:
  db2-data:
